sudo: required
dist: trusty
language: generic
compiler:
  - gcc
notifications:
  email:
    on_failure: always
    recipients:
      - shaun.edwards@gmail.com
env:
  global:
    - CATKIN_CONFIG="--extend /opt/ros/kinetic --blacklist motoman_bmda3_support motoman_csda10f_moveit_config motoman_csda10f_support motoman_epx_support motoman_experimental motoman_gp12_support motoman_gp7_support motoman_gp8_support motoman_mh12_support motoman_mh50_support motoman_motomini_support motoman_mpl80_moveit_config motoman_mpl_support moveit_ros_planning_interface moveit_experimental moveit_planners_chomp moveit_setup_assistant moveit_ros_manipulation moveit_ros_visualization motoman_driver moveit_chomp_optimizer_adapter moveit_ros_warehouse moveit_planners_ompl moveit_ros_benchmarks moveit_ros_move_group motoman_sda10f_support motoman_sia10d_support motoman_sia10f_support motoman_sia20d_moveit_config motoman_sia20d_support motoman_sia5d_moveit_config motoman_sia5d_support motoman_sia5d_moveit_config test_tf2 --cmake-args -DCMAKE_BUILD_TYPE=Release"
  matrix:
    - ROS_DISTRO="kinetic" UPSTREAM_WORKSPACE=file  ROSINSTALL_FILENAME=.travis.rosinstall
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
